name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: prod

    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Create .env file
        run: |
          echo "${{ secrets.OSU_CLIENT_ID }}" > .env
          echo "${{ secrets.OSU_CLIENT_SECRET }}" >> .env
          echo "${{ secrets.OSU_DEFAULT_USER }}" >> .env
          echo "${{ secrets.ALLOWED_ORIGINS }}" >> .env

      - name: Restart with pm2
        run: pm2 restart josh-playground-api || pm2 start dist/index.js --name josh-playground-api
